name: drum4
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4777abc_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - icu=78.2=hb1525cb_0
  - ld_impl_linux-aarch64=2.45=default_h1979696_105
  - libffi=3.5.2=hd65408f_0
  - libgcc=15.2.0=h8acb6b2_16
  - libgcc-ng=15.2.0=he9431aa_16
  - libgomp=15.2.0=h8acb6b2_16
  - liblzma=5.8.2=he30d5cf_0
  - liblzma-devel=5.8.2=he30d5cf_0
  - libnsl=2.0.1=h86ecc28_1
  - libsqlite=3.51.2=h10b116e_0
  - libstdcxx=15.2.0=hef695bb_16
  - libuuid=2.41.3=h1022ec0_0
  - libxcrypt=4.4.36=h31becfc_1
  - libzlib=1.3.1=h86ecc28_2
  - ncurses=6.5=ha32ae93_3
  - openssl=3.6.0=h8e36d6e_0
  - pip=24.3.1=pyh8b19718_0
  - python=3.8.20=hbf90c55_2_cpython
  - readline=8.3=hb682ff5_0
  - setuptools=75.3.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h561c983_103
  - wheel=0.45.1=pyhd8ed1ab_0
  - xz=5.8.2=hd704e39_0
  - xz-gpl-tools=5.8.2=hd704e39_0
  - xz-tools=5.8.2=he30d5cf_0
  - zstd=1.5.7=h85ac4a6_6
  - pip:
      - annotated-types==0.7.0
      - anyascii==0.3.3
      - anyio==4.5.2
      - audioread==3.0.1
      - babel==2.17.0
      - backports-zoneinfo==0.2.1
      - boto3==1.37.38
      - botocore==1.37.38
      - cached-path==1.4.0
      - certifi==2026.1.4
      - cffi==1.17.1
      - charset-normalizer==3.4.4
      - click==8.1.8
      - cmake==4.2.1
      - cn2an==0.5.23
      - dateparser==1.1.8
      - decorator==5.2.1
      - deprecated==1.3.1
      - distance==0.1.3
      - docopt==0.6.2
      - eng-to-ipa==0.0.2
      - exceptiongroup==1.3.1
      - filelock==3.12.4
      - fsspec==2025.3.0
      - fugashi==1.4.3
      - g2p-en==2.1.0
      - g2pkk==0.1.2
      - google-api-core==2.29.0
      - google-auth==2.47.0
      - google-cloud-core==2.5.0
      - google-cloud-storage==2.19.0
      - google-crc32c==1.5.0
      - google-resumable-media==2.8.0
      - googleapis-common-protos==1.72.0
      - gruut==2.4.0
      - gruut-ipa==0.13.0
      - gruut-lang-en==2.0.1
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.16.4
      - idna==3.11
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - inflect==7.4.0
      - jaconv==0.4.1
      - jamo==0.4.1
      - jieba==0.42.1
      - jinja2==3.1.6
      - jmespath==1.0.1
      - joblib==1.4.2
      - jsonlines==1.2.0
      - langid==1.1.6
      - lazy-loader==0.4
      - librosa==0.11.0
      - llvmlite==0.41.1
      - loguru==0.7.3
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - mdurl==0.1.2
      - mecab-python3==1.0.12
      - more-itertools==10.5.0
      - mpmath==1.3.0
      - msgpack==1.1.1
      - networkx==3.1
      - nltk==3.9.1
      - num2words==0.5.14
      - numba==0.58.1
      - numpy==1.24.4
      - ollama==0.6.1
      - openai-whisper==20250625
      - packaging==25.0
      - platformdirs==4.3.6
      - pooch==1.8.2
      - proces==0.1.7
      - proto-plus==1.27.0
      - protobuf==5.29.5
      - pyasn1==0.6.2
      - pyasn1-modules==0.4.2
      - pycparser==2.23
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - pygments==2.19.2
      - pykakasi==2.3.0
      - pypinyin==0.55.0
      - python-crfsuite==0.9.11
      - python-dateutil==2.9.0.post0
      - python-mecab-ko==1.3.7
      - python-mecab-ko-dic==2.1.1.post2
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2024.11.6
      - requests==2.32.4
      - rich==13.9.4
      - rsa==4.9.1
      - s3transfer==0.11.5
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - six==1.17.0
      - sniffio==1.3.1
      - sounddevice==0.5.3
      - soundfile==0.13.1
      - soxr==0.3.7
      - sympy==1.13.3
      - threadpoolctl==3.5.0
      - tiktoken==0.7.0
      - tokenizers==0.13.3
      - torch==2.1.0a0+41361538.nv23.6
      - tqdm==4.67.1
      - transformers==4.27.4
      - typeguard==4.4.0
      - typing-extensions==4.13.2
      - tzlocal==5.2
      - unidecode==1.4.0
      - unidic-lite==1.0.8
      - urllib3==1.26.20
      - wrapt==2.0.1
      - zipp==3.20.2
prefix: /home/shy/miniforge3/envs/drum4
